### ISSUE TITLE
item稀疏度分析

### ISSUE THREAD

**Issue by TangJiakai** [HKUDS/AdaGCL#2]
您好，请问基于item交互数量分析Data Sparsity的代码如何实现呢？可否给出该部分source code呢？因为原文仅有的描述，我并不知道该如何实现，谢谢！

**Comment by yangqin-jiang** [comment]
您好，

感谢您对我们的工作感兴趣。Data Sparsity的分析具体地，我们根据user或者item在训练集中的交互数量来分组，之后在测试集中针对分好组的user和item来做评估，也就是说模型还是在完整的训练集上训练的，只是评估所用的测试集是原本测试集的不同子集。

具体的代码部分，我们是在Datahandler.py文件中添加根据user或者item在训练集中的交互数量分组，并在测试集中根据分组情况过滤的代码，以下是相关函数方法：
``` Python
def filter4SparseTest(self, trnMat, tstMat, usr=True):
	stat = np.squeeze(np.array(np.sum(trnMat != 0, axis=-1 if usr else 0)))
	idct = (stat >= args.nb_min) * (stat < args.nb_max)
	pckNodeSet = set(np.squeeze(np.argwhere(idct)))
	print(len(pckNodeSet))
	print("min : ", args.nb_min)
	print("max : ", args.nb_max)
	def filterTst(tstMat, pckNodeSet, usr=True):
		row = tstMat.row
		col = tstMat.col
		data = tstMat.data
		newRow = []
		newCol = []
		newData = []
		rowOrCol = row if usr else col
		for i, elem in enumerate(rowOrCol):
			if elem in pckNodeSet:
				newRow.append(row[i])
				newCol.append(col[i])
				newData.append(data[i])
		return coo_matrix((newData, (newRow, newCol)), shape=tstMat.shape)
	return filterTst(tstMat, pckNodeSet, usr)
```
由于此部分代码是与我们Datahandler.py中其余部分适配的，所以您可能没法直接拿来使用，但是我相信这些代码能帮助您理解这部分处理的具体流程。

希望此回答对您有帮助，如果还有疑问，欢迎沟通。

**Comment by TangJiakai** [comment]
不，用户分组这个好说，如何计算分组的metrics这部分代码希望您能发一下，希望您能给出源代码，帮助我复现，谢谢！

**Comment by yangqin-jiang** [comment]
您好，

上述filter4SparseTest()函数最后返回的是分组后的测试集，计算分组的metrics这部分和不分组情况下计算整个user集合metrics的方法是一致的，都是通过main.py中testEpoch()这个函数进行的，可以理解为在做稀疏度分组测试时，把原本完整的用户测试集合换成了分组后的用户测试集合，我们在做实验的时候也只是额外通过上述filter4SparseTest()来分组用户，其余部分的代码都和不分组情况下的代码一致，我们也已经放在本代码仓库中了。

希望此回答对您有帮助，如果还有疑问，欢迎沟通。

**Comment by TangJiakai** [comment]
emm 那那个分组物品呢，分组用户很简单，每个组用户各自取平均就好了，但是物品方可不这么简单哪，没事，我自己推出来了。

**Comment by yangqin-jiang** [comment]
嗯嗯，物品侧的实验也是类似的，同样可以用前面给的代码来获得测试集合，filter4SparseTest(self, trnMat, tstMat, usr=True)这边，usr设置为False即为筛选出不同交互数量的item对应的测试集，获得测试集后，之后的评估metrics都是一致的，没有做变动。
