### ISSUE TITLE
可视化

### ISSUE THREAD

**Issue by hunaghuohui** [HKUDS/AdaGCL#3]
你好可以提供可视化实验的代码吗

**Comment by yangqin-jiang** [comment]
你好，

感谢您对我们工作的关注。可视化实验没有完整的一套代码，只需要几个简单的步骤和处理脚本即可完成。具体地，我们先训练AdaGCL，之后保存训练好的user和item embedding，再利用sklearn.manifold中的TSNE对embedding进行降维操作（降到2维），之后对降维后的数据使用KMeans的方式进行聚类，根据数据点的类别赋予不同的颜色，最后使用pyplot工具进行可视化绘图。整个流程都可以通过使用对应的python库实现。

希望这个回答能够对你有帮助。

**Comment by hunaghuohui** [comment]
好的谢谢
