### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by akajinchen** [HKUDS/AdaGCL#5]
https://github.com/HKUDS/AdaGCL/blob/6359f1ed568bf3f99d6351848b9a0c7391c1c93f/Model.py#L137
第二个batch就会报错 是什么情况呢

**Comment by yangqin-jiang** [comment]
你好，是在项目提供的数据集运行时出错吗，如果是的话是哪个数据集，以及具体是什么报错信息。

**Comment by akajinchen** [comment]
> 你好，是在项目提供的数据集运行时出错吗，如果是的话是哪个数据集，以及具体是什么报错信息。
感谢回复，已经解决，但是我发现模型在稍微大的数据集上就会爆显存，有没有什么好的方法缓解呢

**Comment by yangqin-jiang** [comment]
AdaGCL由于需要通过VGAE及图去噪模型对UI图进行重建，这两个图重建部分都会涉及UI图边的处理，其空间复杂度与边数相关，因此在边数量较多（较稠密）的图上运行时会占用较大显存且较慢。本工作的三个数据集上的实验均是在3090 (24G)上完成，如果显存较小，可以尝试着调小batch_size试试，这可能会导致模型需要更多的epoch来达到收敛。

前面提到的图重建部分，VGAE和去噪这两个模块目前都是一次性将整个UI图的所有边进行处理，这边也可以将边以batch的形式进行处理，以降低显存开销，不过这需要对代码进行一定程度的修改。

**Comment by akajinchen** [comment]
> AdaGCL由于需要通过VGAE及图去噪模型对UI图进行重建，这两个图重建部分都会涉及UI图边的处理，其空间复杂度与边数相关，因此在边数量较多（较稠密）的图上运行时会占用较大显存且较慢。本工作的三个数据集上的实验均是在3090 (24G)上完成，如果显存较小，可以尝试着调小batch_size试试，这可能会导致模型需要更多的epoch来达到收敛。
> 
> 前面提到的图重建部分，VGAE和去噪这两个模块目前都是一次性将整个UI图的所有边进行处理，这边也可以将边以batch的形式进行处理，以降低显存开销，不过这需要对代码进行一定程度的修改。

感谢回复~
