### ISSUE TITLE
Question in the dataloader

### ISSUE THREAD

**Issue by fanglin1** [HKUDS/AdaGCL#6]
In the TrnData class of the DataHandler.py file, the self.negSampling() function should be added during initialization, otherwise the generated negative samples may all be zeros.

**Comment by yangqin-jiang** [comment]
Hi,

Thanks for your questions. At the beginning of the training process, self.negSampling() function will be called to generate negative samples 
https://github.com/HKUDS/AdaGCL/blob/6359f1ed568bf3f99d6351848b9a0c7391c1c93f/Main.py#L78

**Comment by fanglin1** [comment]
I'm sorry for my ill-considered question, as I didn't entirely check your code. Besides, thank you for your detailed reply and wish you a happy life!
